//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tax2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tax2Entities : DbContext
    {
        public tax2Entities()
            : base("name=tax2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sotrudnik> sotrudnik { get; set; }
        public DbSet<tc> tc { get; set; }
        public DbSet<tip_vizova> tip_vizova { get; set; }
        public DbSet<vizov> vizov { get; set; }
        public DbSet<zakaz> zakaz { get; set; }
    }
}
