//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tax2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc
    {
        public tc()
        {
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int id { get; set; }
        public string color { get; set; }
        public int nomer { get; set; }
        public string marka { get; set; }
    
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
