//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tax2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tip_vizova
    {
        public tip_vizova()
        {
            this.vizov = new HashSet<vizov>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool vxod_vixod { get; set; }
    
        public virtual ICollection<vizov> vizov { get; set; }
    }
}
