//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tax2
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public zakaz()
        {
            this.vizov = new HashSet<vizov>();
        }
    
        public int id { get; set; }
        public int id_sotrudnika { get; set; }
        public int id_TC { get; set; }
        public string A { get; set; }
        public string B { get; set; }
    
        public virtual sotrudnik sotrudnik { get; set; }
        public virtual tc tc { get; set; }
        public virtual ICollection<vizov> vizov { get; set; }
    }
}
